### PR TITLE
Auto swap relay chain token for TEER for xcm execution fees and fix asset trap on integritee cousin

### LINKED ISSUE #329: [XCM] autoswap fees
Now that we allow arbitrary XCM execution, we need to properly solve XCM fees.

Currently we accept TEER and the relay chain token to pay fees, but in the case of DOT, the fees will be excessive because we simple take fees at nominal value irrespective of TEER, KSM, DOT. So DOT fee is 100x than KSM because of this:

https://github.com/integritee-network/parachain/blob/a3c9655c6f0211bf39f0279969cc1da049058f60/polkadot-parachains/integritee-polkadot/src/xcm_config.rs#L307-L323

What we want is to rather only accept TEER, but swap DOT for TEER first, like AH does:

https://github.com/polkadot-fellows/runtimes/blob/d41d01f68e3b23340efce3d9156fbabe27fd877c/system-parachains/asset-hubs/asset-hub-polkadot/src/xcm_config.rs#L426-L448

### LINKED ISSUE #338: [porteer] trapped assets on destination
We successfully bridged TEER on zombienet, but we get trapped assets on destination.

This is likely due to the missing `SetAppendix` before `Transact`:

https://github.com/integritee-network/parachain/blob/87f9cb2bc88420a3d42a536132cef8e0372b06be/polkadot-parachains/common/src/porteer.rs#L151-L159

beneficiary should be `treasury`

and while at it, please rename the type argument `IntegriteePolkadotCall` to `IntegriteeCall` to not assume a particular direction of the port

### PR DESCRIPTION
**Pull request by clangenb**
* Closes #338 
* Closes #329

### CODE REVIEW

File: polkadot-parachains/common/src/porteer.rs [hunk 1]
```diff
@@ -145,17 +153,28 @@ fn ah_cousin_xcm<Call, IntegriteePolkadotCall: Encode>(
...
-	}])
+	Xcm(vec![
+		SetAppendix(Xcm(vec![
+			RefundSurplus,
+			DepositAsset {
+				assets: AssetFilter::Wild(WildAsset::All),
+				beneficiary: AccountId32 { network: None, id: integritee_cousin_treasury.into() }
+					.into(),
+			},
+		])),
```
Comment (clangenb) [inline polkadot-parachains/common/src/porteer.rs:173]: Fixes #338

File: polkadot-parachains/common/src/fee.rs [hunk 2]
```diff
@@ -28,13 +30,28 @@ pub const TARGET_BLOCK_FULLNESS: Perbill = Perbill::from_percent(25); // <- unus
 ///   - Setting it to `0` will essentially disable the weight fee.
 ///   - Setting it to `1` will cause the literal `#[weight = x]` values to be charged.
 pub struct WeightToFee;
-impl WeightToFeePolynomial for WeightToFee {
+impl frame_support::weights::WeightToFee for WeightToFee {
```
Comment (clangenb) [inline polkadot-parachains/common/src/fee.rs:33]: Updated with the current definition in the asset-hub-kusama
